# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        build:
          context: ./src/main/resources/docker
          dockerfile: db_dockerfile
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: passwd
        ports:
          - 5432:5432
#    app:
#        build:
#          context: ./src/main/resources/docker
#          dockerfile: app_dockerfile
#        restart: always
#        depends_on:
#          - "db"
#        ports:
#          - 8123:8123

